 # Install Apache server
  - name: Install Apache
    yum: name=httpd state=present

  - name: Start Apache
    service: name=httpd state=started enabled=yes

  - name: Config Apache
    template: src=httpd-repo.conf.j2 dest=/etc/httpd/conf/httpd.conf
    notify: restart apache



