---

- debug: msg="
        This is 
        multiline  {{ inventory_hostname }} 
        I'm runnnig {{ ansible_eth1.ipv4.address }}
      "

- debug: msg="Host  {{ inventory_hostname }}"

- debug: msg="I'm runnnig {{ ansible_eth1.ipv4.address }}"

- debug: msg="http://repo.{{ ansible_all_ipv4_addresses[0] }}.xip.io/ or http://repo.{{  ansible_all_ipv4_addresses[1] }}.xip.io/"
#  with_items:
#    - {{ ansible_all_ipv4_addresses[0] }}
#    - {{ ansible_all_ipv4_addresses[1] }}

