---

- name: Install Apache Server
  yum: name=httpd state=present

- name: Enabled Module rewrite
  apache2_module: name=rewrite state=present

- name: Start Apache
  service: name=httpd state=started enabled=yes

