---
- name: Install Oracle JDK
  yum: name=jdk state=present

- name: install java alternatives
  alternatives: name="java" path="/usr/java/jdk{{ jdk_version }}/jre/bin/java" link="/usr/bin/java"

- name: set environments
  lineinfile:  dest="/etc/environment" line='{{ item }}'
  with_items:
  - 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ extra_path }}"'
  - 'JAVA_HOME="/usr/java/jdk{{ jdk_version }}"'
  - 'JRE_HOME="/usr/lib/jvm/jre-1.7.0"'