---
- name: Install Jenkins
  yum: state=present name={{ item }}
  with_items:
  - jenkins
  - git

- name: Start Jenkins
  service: name=jenkins state=started enabled=yes

- name: Install plugins
  get_url: url=http://updates.jenkins-ci.org/latest/{{ item }}.hpi dest={{ jenkins_home }}/plugins/{{ item }}.hpi
  with_items:
  - git
  - git-client
  - scm-api
  - git-tag-message
  environment:
   http_proxy: "http://192.168.5.103:8080/"
   https_proxy: "http://192.168.5.103:8080/"
   ftp_proxy: "http://192.168.5.103:8080/"

- name: Config Jenkins Jobs
  file: path={{ jenkins_home }}/jobs/oms/ mode=0775 owner=jenkins group=jenkins state="directory" recurse=yes
  template: src=config-jobs.xml dest={{ jenkins_home }}/jobs/oms/config.xml

- name: Config Jenkins
  template: src={{ item }} dest={{ jenkins_home }}/{{ item }}
  with_items:
  - config.xml
  - hudson.tasks.Maven.xml
  - jenkins.mvn.GlobalMavenConfig.xml
  notify: restart jenkins