---
jenkins_home: /var/lib/jenkins
jenkins_version: 1.650
jenkins_user: jenkins
jenkins_group: jenkins
jenkins_security_user: devops
repo_host: repo
# Plugins
_jenkins_plg:
  - git
  - git-client
  - git-parameter
  - scm-api
  - git-tag-message
  - publish-over-ssh
  - syslog-logger
# Config files templates
_jenkins_cfg:
  - config.xml
  - hudson.tasks.Maven.xml
  - jenkins.mvn.GlobalMavenConfig.xml
  - jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml
  - org.jenkinsci.plugins.sysloglogger.SyslogLoggerPlugin.xml
# Jenkins Jobs
_jenkins_jbs:
  - oms-master
  - oms-dev
syslog_srv: 127.0.0.1
syslog_prt: 514