---
  - name: run zabbix-server
    hosts: zabbix
    become: yes
    user: vagrant

    roles:
      - setlocalrepo
#      - simple-httpd
      - { role: apache, apache_conf: zabbix }
#      - {role: apache2, action: 'install'}
#      - {role: apache2, action: 'virtualhost', vhost_name: 'zabbix', vhost_dir: '/usr/share/zabbix'}
#      - apache
      - simple-mariadb
#      - mysql
#      - zabbixcreatedb
      - zabbixserver
#  - include: roles/zabbixserver/tasks/main.yml
      - zabbixcreatedb
      - zabbixcreategroup
   #   - zabbixcreatehost 
      - { role: zabbixcreatehost, host_name: 'ansible', host_group: 'BALANCER', host_ip: '192.168.22.10'}
      - { role: zabbixcreatehost, host_name: 'balancer', host_group: 'BALANCER', host_ip: '192.168.22.11'}
      - { role: zabbixcreatehost, host_name: 'jenkins', host_group: 'JENKINS', host_ip: '192.168.22.12'}
      - { role: zabbixcreatehost, host_name: 'repo', host_group: 'REPO', host_ip: '192.168.22.14'}
      - { role: zabbixcreatehost, host_name: 'logs', host_group: 'LOGSERVER', host_ip: '192.168.22.11'}
      - { role: zabbixcreatehost, host_name: 'web1', host_group: 'WEB', host_ip: '192.168.22.21'}
      - { role: zabbixcreatehost, host_name: 'web2', host_group: 'WEB', host_ip: '192.168.22.22'}
      - { role: zabbixcreatehost, host_name: 'web3', host_group: 'WEB', host_ip: '192.168.22.23'}
      - { role: zabbixcreatehost, host_name: 'db1', host_group: 'DB', host_ip: '192.168.22.31'}
      - { role: zabbixcreatehost, host_name: 'db2', host_group: 'DB', host_ip: '192.168.22.32'}
      - { role: zabbixcreatehost, host_name: 'db3', host_group: 'DB', host_ip: '192.168.22.33'}


