---
  - name: run zabbix-server
    hosts: zabbix
    become: yes
    user: vagrant

    roles:
#      - simple-httpd
      - apache
#      - simple-mariadb
      - mysql
#      - zabbixcreatedb
      - zabbixserver
#  - include: roles/zabbixserver/tasks/main.yml
      - zabbixcreatedb
      - zabbixcreategroup
      
